eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# con este configuracion hace que el config server no anule las propiedaddes del sistema
spring:
  cloud:
    config:
      override-system-properties: false

# Zipkin por defecto usa el puerto 9411 (ver dockercompose)
management:
     tracing:
       sampling:
         probability: 1.0