spring:
  data:
    mongodb:
      username: erich
      password: erich
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090