spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: erich
    password: erich
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments